FROM node:16

RUN git clone https://github.com/X-Profiler/xtransit-manager
WORKDIR /xtransit-manager
RUN npm install
COPY ./env /xtransit-manager/config/
COPY ./config.local.js /xtransit-manager/config/

CMD npx egg-scripts start --title=egg-server-xtransit-manager --port=7543 --workers=4
