version: "3.5"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - backend

  mysql:
    image: wtfsql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=whatsoever
    networks:
      - backend

  xprofiler-console:
    image: wtfconsole
    container_name: xprofiler-console
    restart: always
    env_file:
      - ./env/mysql.env
      - ./env/redis.env
      - ./env/endpoints.env
    networks:
      - backend
    ports:
      - 7443:7443

  xtransit-manager:
    image: wtfmanager
    container_name: xtransit-manager
    restart: always
    env_file:
      - ./env/mysql.env
      - ./env/redis.env
      - ./env/mail.env
      - ./env/endpoints.env
    networks:
      - backend

  xtransit-server:
    image: wtfserver
    container_name: xtransit-server
    restart: always
    env_file:
      - ./env/endpoints.env
    networks:
      - backend
    ports:
      - 9090:9090


networks:
  backend:
    name: backend
    driver: bridge