FROM node:16

RUN git clone https://github.com/X-Profiler/xtransit-server
WORKDIR /xtransit-server
RUN npm install
COPY ./env /xtransit-server/config/
COPY ./config.local.js /xtransit-server/config/

CMD npx egg-scripts start --title=egg-server-xtransit-server --port=9090
