FROM node:16

RUN git clone https://github.com/X-Profiler/xprofiler-console
WORKDIR /xprofiler-console
RUN npm install
COPY ./env /xprofiler-console/config/
COPY ./config.local.js /xprofiler-console/config/

CMD npx egg-scripts start --title=egg-server-xprofiler-console --port=7443 --workers=4
